project:
  type: website

website:
  title: "Delta Residents Survey"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: documentation.qmd
        text: Docs
      # - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

