---
title: "Introduction"
---

The Delta Residents Survey (DRS) was conducted in the first quarter of 2023, reaching over 2,300 Delta and Delta-adjacent residents of the California Delta. After an initial round of data cleaning, this left us with 2,208 usable responses. Among other things, the survey included questions on well-being and environmental changes.

## Source Code

In order to facilitate other researchers to utilize the DRS data more fully, we have provided a [DRS Repository](https://github.com/ktomari/DeltaResidentsSurvey). This GitHub repository includes R scripts needed to load and do basic analyses of the survey data from 2023.

We also provide documentation for the source code [here](/DeltaResidentsSurvey/doc_drs_functions.html).

## Summary Report

The summary report is temporarily available [here](https://ucdavis.box.com/s/34kmt02f87ohhbpij9hu0iesubm15781), and will become available on the Delta Stewardship Council website in the future. A screen-reader friendly version will be uploaded as well. Additional materials will be posted as they become available. Please check back in early 2024.

## Data

The publicly available data set will be published in the coming months (late 2023 to early 2024).